[package]
name = "wav_viewer"
version = "0.1.0"
authors = ["Decodetalkers"]
edition = "2024"
publish = false

[dependencies]
iced = { version = "0.14.0", features = ["debug", "canvas", "image", "tokio"] }
pipewire = "0.9.2"

rand = "0.9.2"
realfft = "3.5.0"
tracing-subscriber = "0.3"
